fix(examples): add fixes to angular architect
This PR adds;
1)  `lint` as a target
2) Changes npm script to use bazelisk
3) Disables `forkTypeChecker` as under Windows this currently errors out with:
```
Error: spawn C:\users\alag\_bazel_alag\jeen2jsq\external\build_bazel_rules_nodejs\internal\node\_node_bin\node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn C:\\users\\alag\\_bazel_alag\\jeen2jsq\\external\\build_bazel_rules_nodejs\\internal\\node\\_node_bin\\node',
  path: 'C:\\users\\alag\\_bazel_alag\\jeen2jsq\\external\\build_bazel_rules_nodejs\\internal\\node\\_node_bin\\node',
  spawnargs: [
    '--require',
    'C:/users/alag/_bazel_alag/jeen2jsq/external/build_bazel_rules_nodejs/internal/node/node_patches.js',
    '--preserve-symlinks',
    '--preserve-symlinks-main',
    'c:\\users\\alag\\_bazel~1\\jeen2jsq\\execroot\\angula~1\\node_modules\\@ngtools\\webpack\\src\\type_checker_worker.js',
    '9d93e901-158a-4cf9-ba1b-2f0582ffcfeb'
  ]
}
```