Use `headers` attribute for toolchains only if it is set
This effectively establishes backward compatibility with users of previous
rules_nodejs that create custom toolchains and do not pass the `headers`
attribute to `node_toolchain` which would otherwise fail with:

```
ERROR: /.../external/rules_haskell_nix_node_toolchain/BUILD:4:15: in node_toolchain rule @rules_haskell_nix_node_toolchain//:node_nixpkgs:
Traceback (most recent call last):
  File "/.../external/rules_nodejs/nodejs/toolchain.bzl", line 102, column 43, in _node_toolchain_impl
     "CcInfo": ctx.attr.headers[CcInfo],
Error: type \'NoneType\' has no operator [](Provider)
```