fix: yarn_install failure if yarn is a dependency (#1581)
This fixes a regression in 1.2.0 where the repository rule generated shell script `yarn` in the root of the external repository created by yarn_install conflicts with the npm package `yarn` directory that generate_build_files.js wants to create. The error observed was:
```
Error: ENOTDIR: not a directory, mkdir 'yarn/bin'
    at Object.mkdirSync (fs.js:823:3)
    at mkdirp (/private/var/tmp/_bazel_pryan/7a08068b62d3caa281adb87aa0ce207a/external/npm/generate_build_file.js:81:16)
    at writeFileSync (/private/var/tmp/_bazel_pryan/7a08068b62d3caa281adb87aa0ce207a/external/npm/generate_build_file.js:89:9)
    at generatePackageBuildFiles
```

Also fixes the same potential problem with the repository rule generated `npm` shell script.