build(examples): update examples/angular & examples/angular_view_engine angular deps
* update examples/angular to latest @angular 9.0.0-rc.7
* update examples/angular to latest @angular/cdk & @angular/material 9.0.0-rc.6
* examples/angular hello-world.component.spec.ts updated to no longer use aotSummaries in TestBed.configureTestModule (that ViewEngine pattern now breaks the build)
* cleanup deps in examples/angular since with Ivy ngfactory files no longer pull in extra deps

* update examples/angular_view_engine to latest @angular 8.2.14
* update examples/angular_view_engine to latest @angular/bazel 9.0.0-rc.7
* update examples/angular_view_engine to @angular/cli 8.3.12

NB: @angular/cli 8.3.13+ causes error:
```
node_modules/@angular/cli/commands/add-impl.d.ts(7,37): error TS2307: Cannot find module '../../../../dist-schema/packages/angular/cli/lib/config/schema'.
error Command failed with exit code 1.
```