Fix compilation issue due to string mismatch
Facing the following error when building using Bazel typescript

```
external/build_bazel_rules_typescript/internal/BUILD.bazel:49:4: Action external/build_bazel_rules_typescript/internal/tsc_wrapped/cache.js failed (Exit 2): tsc.sh failed: error executing command bazel-out/host/bin/external/npm/typescript/bin/tsc.sh --declaration -p external/build_bazel_rules_typescript/internal/tsconfig.json --outDir ... (remaining 3 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox tsc.sh failed: error executing command bazel-out/host/bin/external/npm/typescript/bin/tsc.sh --declaration -p external/build_bazel_rules_typescript/internal/tsconfig.json --outDir ... (remaining 3 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/build_bazel_rules_typescript/internal/tsc_wrapped/compiler_host.ts(372,55): error TS2769: No overload matches this call.
  Overload 1 of 3, '(path: string | number | Buffer | URL, options?: { encoding?: null | undefined; flag?: string | undefined; } | null | undefined): Buffer', gave the following error.
    Argument of type '"UTF-8"' is not assignable to parameter of type '{ encoding?: null | undefined; flag?: string | undefined; } | null | undefined'.
  Overload 2 of 3, '(path: string | number | Buffer | URL, options: "ascii" | "utf8" | "utf-8" | "utf16le" | "ucs2" | "ucs-2" | "base64" | "latin1" | "binary" | "hex" | { encoding: BufferEncoding; flag?: string | undefined; }): string', gave the following error.
    Argument of type '"UTF-8"' is not assignable to parameter of type '"ascii" | "utf8" | "utf-8" | "utf16le" | "ucs2" | "ucs-2" | "base64" | "latin1" | "binary" | "hex" | { encoding: BufferEncoding; flag?: string | undefined; }'.
  Overload 3 of 3, '(path: string | number | Buffer | URL, options?: "ascii" | "utf8" | "utf-8" | "utf16le" | "ucs2" | "ucs-2" | "base64" | "latin1" | "binary" | "hex" | (BaseEncodingOptions & { ...; }) | null | undefined): string | Buffer', gave the following error.
    Argument of type '"UTF-8"' is not assignable to parameter of type '"ascii" | "utf8" | "utf-8" | "utf16le" | "ucs2" | "ucs-2" | "base64" | "latin1" | "binary" | "hex" | (BaseEncodingOptions & { flag?: string | undefined; }) | null | undefined'.
```

per https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7789a59cad6d4630db8116abe6b21ca1255df507/types/node/globals.d.ts#L74, it support "utf-8" and not "UTF-8"