fix(typescript): repair error reporting when a ts_project is missing declaration=True
Now prints this like it should:
```
ERROR: /home/alexeagle/Projects/rules_nodejs/examples/web_testing/BUILD.bazel:16:11: in deps attribute of ts_project rule //:tests: '//:lib' does not have mandatory providers: 'DeclarationInfo' or '_ValidOptionsInfo'. Since this rule was created by the macro 'ts_project_macro', the error might have been caused by the macro implementation
```