Turn PatternKind into a non-const enum.
PatternKind is later re-exported. const enums cannot be re-exported, as they are removed at compile time and don't exist at runtime.

This fixes a compilation error in TS3.6:

conformance_pattern_rule.ts:57:9 - error TS2475: 'const' enums can only be used in property or index access expressions or the right hand side of an import declaration or export assignment or type query.

PiperOrigin-RevId: 270688010