fix(npm_package): do not write external dep files to same location
Currently the `npm_package` acceps an arbitary list of targets that will be built as `dependencies`. Some of these dependencies are within the Bazel package that defines the `npm_package` and should be also copied into the `npm_package`.

Transitive dependencies (or explicit deps) which are outside of the current package are currently passed to the `packager` and accidentally written to the same location (this causes exceptions) and since these output actions aren't having any effect, we should not even pass these files to the `packager` in order to improve performance and fix exceptions like:

```
ERROR: /home/circleci/ng/src/lib/schematics/BUILD.bazel:34:1: SkylarkAction src/lib/schematics/npm_package failed (Exit 1)
Error: EEXIST: file already exists, mkdir 'bazel-out/k8-fastbuild/bin/src/external/matdeps/node_modules/@schematics/angular/component/files/__name@dasherize@if-flat__'
    at Object.mkdirSync (fs.js:731:3)
    at mkdirp (/home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular_material/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/npm_package/packager.runfiles/build_bazel_rules_nodejs/internal/npm_package/packager.js:23:8)
    at write (/home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular_material/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/npm_package/packager.runfiles/build_bazel_rules_nodejs/internal/npm_package/packager.js:28:3)
    at main (/home/circleci/.cache/bazel/_bazel_circleci/9ce5c2144ecf75d11717c0aa41e45a8d/execroot/angular_material/bazel-out/host/bin/external/build_bazel_rules_nodejs/internal/npm_package/packager.runfiles/build_bazel_rules_nodejs/internal/npm_package/packager.js:101:5)
```